version: '2.3'

name: 'partners'

services:
  partners:
    image: 'alpine:latest'
    command: /bin/sh -c "echo \"partnership! VAR=$${VAR}\"" 
    env_file: ${PARTNERS_ROOT_PATH:-.}/docker-development.env